CREATE DATABASE MinionsDB

USE MinionsDB

CREATE TABLE Countries(
	Id INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR NOT NULL
)

CREATE TABLE Towns(
	Id INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[CountryCode] INT FOREIGN KEY REFERENCES Countries(Id)
)

CREATE TABLE Minions(
	Id INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[Age] INT NOT NULL,
	[TownId] INT FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE EvilnessFactors(
	Id INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
)

CREATE TABLE Villians(
	Id	INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(255) NOT NULL,
	[EvilnessFactorId] INT FOREIGN KEY REFERENCES EvilnessFactors(Id)
)

CREATE TABLE MinionsVillians(
	MinionId INT FOREIGN KEY REFERENCES Minions(Id),
	VilliansId INT FOREIGN KEY REFERENCES Villians(Id)
)